Name: Debsparsha Dasgupta
Registration No.: 24-27-38
Program: MTech(Data Science)
Assignment No.: 2

Question 1

In [1]:
import numpy as np

#a
var1 = np.arange(0, 31)
print("var1:\n", var1)
print("Shape of var1:", var1.shape)

#b
var2 = var1.reshape(31, 1)  
print("\nvar2:\n", var2)
print("Shape of var2:", var2.shape)

#c
var3 = var1.reshape(1, 31, 1)
print("\nvar3:\n", var3)
print("Shape of var3:", var3.shape)

#d
var2[1, 0] = -1
print("\nModified var2:\n", var2)
print("Has var1 changed?\n", var1)
print("Has var3 changed?\n", var3)

#e
## i
sum3_axis_1 = np.sum(var3, axis=1)
print("\nSum of var3 over its second dimension:\n", sum3_axis_1)

##ii
sum3_axis_2 = np.sum(var3, axis=2)
print("\nSum of var3 over its third dimension:\n", sum3_axis_2)

##iii
sum3_axes_0_2 = np.sum(var3, axis=(0, 2))
print("\nSum of var3 over both its first and third dimensions:\n", sum3_axes_0_2)

#f
##i
second_row_var2 = var2[1, :]
print("\nSecond row of var2:\n", second_row_var2)

##ii
last_column_var2 = var2[:, -1]
print("\nLast column of var2:\n", last_column_var2)

##iii
top_right_2x2_submatrix_var2 = var2[:2, -2:]
print("\nTop right 2x2 submatrix of var2:\n", top_right_2x2_submatrix_var2)



var1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1: (31,)

var2:
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Shape of var2: (31, 1)

var3:
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]
Shape of var3: (1, 31, 1)

Modified var2:
 [[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Has var1 changed?
 [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Has var3 changed?
 [[[ 0]
  [-1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 

Question 2

In [2]:
import numpy as np
import numpy.random as npr

#a
vector = np.arange(10) + 1
print("Vector:", vector)

#b
A = vector.reshape(10, 1) + vector
print("\nMatrix A:\n", A)

#c#d
data = np.exp(npr.randn(50, 5))
print("\nData Set:\n", data)

#e
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

print("\nMean of each column:", mean)
print("Standard deviation of each column:", std_dev)

#f
normalized = (data - mean) / std_dev
normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)

print("\nNormalized Mean:", normalized_mean)
print("Normalized Std Dev:", normalized_std)


Vector: [ 1  2  3  4  5  6  7  8  9 10]

Matrix A:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]

Data Set:
 [[12.16765298  2.00073717  1.2346894   8.08885654  0.22381117]
 [ 3.58761141  0.38617313  0.39214489  1.30413681  1.28253663]
 [ 1.43427979  0.35438439  1.10052148  0.95611109  0.65686129]
 [ 0.65504773  0.4106077   0.24358478  1.99375996  3.58291894]
 [ 0.39632254  0.7415062   3.55716603  0.62784414  1.04109038]
 [ 0.49119268  1.81993354  3.26299534  0.25954225  0.87214551]
 [ 0.75191289  3.05278183  0.63764821  0.69813306  8.05907819]
 [ 3.8844609   2.70181792  1.02247653  0.80063849  3.93033655]
 [ 1.04780938  5.2835544   1.48839775  2.16045421  3.13695242]
 [ 0.31653869  1.23633384  0.27929048 

Question 3

In [3]:
import numpy as np
import numpy.linalg as la

#a
def vandermonde(N):
    vec = np.arange(N) + 1
    vander = vec ** np.arange(N).reshape(-1, 1)
    return vander.T

N = 12
vander = vandermonde(N)
print("Vandermonde Matrix for N=12:\n", vander)

#b
x = np.ones(N)
b = np.dot(vander, x)
print("\nVector b:\n", b)

#c
V_inv = la.inv(vander)
x_naive = np.dot(V_inv, b)
print("\nSolution using matrix inversion:\n", x_naive)

#d
x_solve = la.solve(vander, b)
print("\nSolution using solve:\n", x_solve)


Vandermonde Matrix for N=12:
 [[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362

The result from solve is much closer to the actual value of x (all ones), while the result from matrix inversion deviates due to numerical instability.

Github Link: https://github.com/debsparsha98/DebsparshaDasgupta_24-27-38